### ISSUE TITLE
Ignoring source layer loss

### ISSUE THREAD

**Issue by aram200** [CheezBallzPi/hyperdim-fcn#2]
Hi 
I am trying to train the network exactly as you have given. 
-infer.py-
![image](https://user-images.githubusercontent.com/36761121/36896950-fe4c7ddc-1e57-11e8-8f59-d7e7e11a0ce7.png)

but, my process is stopped after 
"Ignoring source layer loss" without any explanation

![image](https://user-images.githubusercontent.com/36761121/36896774-42201786-1e57-11e8-87fe-d224fc98bd2e.png)

any idea please?

**Comment by CheezBallzPi** [comment]
Try using solve.py to train the net.

**Comment by CheezBallzPi** [comment]
Also the Readme is outdated, I’ll probably fix it soon.

**Comment by aram200** [comment]
thank you for your reply!! 
I want to visualize output .. so I used infer.py

**Comment by CheezBallzPi** [comment]
As a high school junior, I barely get time to work on this. infer.py has not been converted to Keras yet, so I suggest you stay away from it.
